name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    if: github.repository_owner == 'solaimon-sharifi' || always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Render deploy via API
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          if [ -z "$RENDER_SERVICE_ID" ] || [ -z "$RENDER_API_KEY" ]; then
            echo "Missing RENDER_SERVICE_ID or RENDER_API_KEY secrets. Skipping deploy.";
            exit 1;
          fi

          echo "Triggering deploy for Render service: $RENDER_SERVICE_ID"
          # Create a new deploy. This uses the Render REST API. The endpoint below is the
          # standard deploy creation endpoint and will start a new deploy for the service.
          # If Render changes their API, update this step per Render docs.
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":true}' \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys")

          if [ "$RESPONSE" -ge 200 ] && [ "$RESPONSE" -lt 300 ]; then
            echo "Render deploy triggered (HTTP $RESPONSE).";
          else
            echo "Render deploy failed (HTTP $RESPONSE).";
            exit 1;
          fi
name: Deploy to Render

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.RENDER_SERVICE_ID }}" ]; then
            echo "Missing secret: RENDER_SERVICE_ID"; exit 1; fi
          if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then
            echo "Missing secret: RENDER_API_KEY"; exit 1; fi

      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering Render deploy for service: $RENDER_SERVICE_ID"
          resp=$(curl -s -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{}' \
            "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys")
          echo "Render response: $resp"
          # Optionally fail if response includes error
          echo "$resp" | grep -i "error" && (echo "Render deploy failed" && exit 1) || echo "Deploy triggered"
