name: Valorant Coach CI

on:
  push:
    paths:
      - 'valorant-coach/**'
      - '.github/workflows/valorant-coach-ci.yml'
  pull_request:
    paths:
      - 'valorant-coach/**'
      - '.github/workflows/valorant-coach-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r valorant-coach/requirements.txt
      - name: Run tests (valorant-coach)
        run: pytest -q -c /dev/null
        working-directory: valorant-coach
